name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install
        run: yarn install
      - name: Check Format
        run: yarn run prettier -c src '*.json' '*.cjs' '*.ts'
      - name: Check Lint
        run: yarn run eslint
      # - name: Tests
      #   run: yarn run test
